[versions]
androidGradlePlugin = "8.13.1"
detekt = "2.0.0-alpha.1"
dotenv = "6.5.1"
gradlePublishPlugin = "2.0.0"
kaml = "0.104.0"
kotlin = "2.2.21"
kotlinPoet = "2.2.0"
kotlinter = "5.3.0"
mockk = "1.14.6"

[libraries]
android-gradle-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "androidGradlePlugin" }
dotenv-kotlin = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv" }
kaml = { group = "com.charleskorn.kaml", name = "kaml", version.ref = "kaml" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinPoet" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
publisher = { id = "com.gradle.plugin-publish", version.ref = "gradlePublishPlugin" }
